development:
  adapter: postgresql
  encoding: unicode
  database: ticket_development
  pool: 5
  username: postgres
  password: yoda-c3po!
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ticket_test
  pool: 5
  username: postgres
  password: yoda-c3po!
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: timetracker_production
  pool: 5
  username: timetracker
  password:
